### ISSUE TITLE
Travis CI setup

### ISSUE THREAD

**Issue by tauchmanovaM** [SemStew/CMS_Django_B181#7]
Potřebuji pomoct s nastavením travis souboru pro kontrolu kódu. Kostra tam je, jen je potřeba upravit na naše nastavení (Django, db).

- [x] Nastavení travisu
- [x] Otestování jeho funkčnosti

**Comment by MarekSuchanek** [comment]
Tohle by mělo jít, když nyní máte `setup.py`

```yaml
language: python
python:
- 3.7 # No other version supported by SemStew :'(
before_install:
- cd SemStew
install:
- python setup.py install
- python manage.py migrate
before_script:
- cd SemStew
script:
- python manage.py test
```
